# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WDJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=300)),
                ('package_id', models.CharField(max_length=300)),
                ('package_content', models.CharField(max_length=1048576)),
            ],
        ),
    ]
