# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsontools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WDJ',
        ),
    ]
