# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdj', '0003_auto_20160404_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wdj',
            options={'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
    ]
